# Generated by Django 3.1.7 on 2021-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.TextField(blank=True),
        ),
    ]
